config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Simple Airbnb", flats_path, style: 'text-decoration: none;' %>
  <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary"  %>
</nav>

<div class="contaier w-100 pl-5 pr-5 pt-2">
  <h1>All our Flats (<%= @flats.size %>)</h1>
  <div class="flat-cards d-flex justify-content-around flex-wrap">
    <% @flats.each do |flat| %>
      <div class="flat-card w-25 m-5 shadow-sm bg-white">
        <div class="flat-card-image" style='background-image: url("https://source.unsplash.com/random/?house"); background-size: cover; height: 200px; background-position: center;'></div>
        <div class="flat-card-info p-3 bg-light">
          <p class="font-weight-bold"><%= flat.name %></p>
          <p class="font-weight-light"><%= flat.address %></p>
          <p><%= flat.number_of_guests %>👥 <%= flat.price_per_night %>€</p>
        </div>
        <div class ="p-3">
          <%= link_to "More info", flat_path(flat), class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<nav class="navbar navbar-light bg-light">
  Simple Airbnb
</nav>
<div class="container w-50">
  <%= simple_form_for @flat do |f| -%>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
    <%= f.input :description %>
    <%= f.submit "Add a Flat", class: "btn btn-primary w-100" %>
  <% end -%>
</div>

app/views/flats/show.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Simple Airbnb", flats_path, style: "text-decoration: none;" %>
  <%= link_to "Add Flat", new_flat_path, class: "btn btn-primary"  %>
</nav>
<div class="" style='background-image: url("https://source.unsplash.com/random/?house"); background-size: cover; height: 400px; background-position: center;'></div>

<div class="container w-75 d-flex justify-content-center align-items-top">
  <div class="info flew-grow-1">
    <div class="m-5 shadow-sm bg-light px-5 py-1">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
    </div>
    <div class="m-5 shadow-sm bg-light px-5 py-1">
      <h2>A bit more about this flat</h2>
      <p><%= @flat.description %></p>
    </div>
    <div class="m-5 shadow-sm bg-light px-5 py-1">
      <h1>Details</h1>
      <p><%= @flat.number_of_guests %>👥 <%= @flat.price_per_night %>€</p>
    </div>
  </div>
  <div class="reservation">
    <div class="m-5 shadow-sm bg-light px-5 py-1">
      <p>Book this place</p>
      <a href="#" class="btn btn-success">Next features</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>